### Shin Godzilla Movie
GET http://localhost:8000/api/guess?it=Shin Godzilla (2016) 1080p Hybrid Bluray REMUX AVC Dual DTS-HD MA 3.1

### The Blob movie
GET http://localhost:8000/api/guess?it=The Blob (1988) (1080p BluRay x265 10bit Tigole).mkv
### The Blob movie alt
GET http://localhost:8000/api/guess?it=The Blob (1988) (1080p BluRay x265 10bit Tigole)/movie.mkv

### Rick and Morty S07E10
GET http://localhost:8000/api/guess?it=Rick.and.Morty.S07E10.Fear.No.Mort.1080p.HMAX.WEB-DL.DDP5.1.H.264-FLUX-poster.jpg
### Rick and Morty S07E10 alt
GET http://localhost:8000/api/guess?it=Rick.and.Morty.S07E10.Fear.No.Mort.1080p.HMAX.WEB-DL.DDP5.1.H.264-FLUX/poster.jpg
### Rick and Morty S07E10 alt 2
GET http://localhost:8000/api/guess?it=rick.and.morty.s07e10.fear.no.mort.1080p.hmax.web-dl.ddp5.1.h.264-flux/poster.jpg

### Death Proof (Guess IT fails, so fallback to OpenAI.)
GET http://localhost:8000/api/guess?it=tmp/Death.Proof.2007.1080p.BluRay.x264-1920/1920-proof.rar

### Fargo Movie
GET http://localhost:8000/api/guess?it=Fargo.1080p.BluRay.x264-1920/1920-proof.rmkv
### Fargo Movie alt
GET http://localhost:8000/api/guess?it=Fargo.1996.1080p.BluRay.x264-1920/1920-fargo.rmkv
### Fargo TV Series
GET http://localhost:8000/api/guess?it=Fargo.S01E01.1080p.BluRay.x264-1920/1920-fargo.rmkv

### Killing Zoe
GET http://localhost:8000/api/guess?it=tmp/Killing.Zoe.1993.1080p.BluRay.x264-LCHD/lchd-kz1080p.rar

### Slow Horses S02 E05
GET http://localhost:8000/api/guess?it=Slow.Horses.S02.NORDiC.720p.WEB-DL.H.265.DD5.1-CiNEMiX/Slow.Horses.S02E05.NORDiC.720p.WEB-DL.H.265.DD5.1-CiNEMiX-poster.jpg

### Slow Horses S03 E01
GET http://localhost:8000/api/guess?it=/mnt/mock-test-files/Slow.Horses.S03.NORDiC.720p.WEB-DL.H.265.DD5.1-CiNEMiX/Slow.Horses.S03E01.NORDiC.720p.WEB-DL.H.265.DD5.1-CiNEMiX.nfo

### American Dad S02 E01
GET http://localhost:8000/api/guess?it=/mnt/mock-test-files/American.Dad.S20E01.1080p.WEBRip.x264-BAE/American.Dad.S20E01.1080p.WEBRip.x264-BAE.mkv

### Final Destination / TheFinal Destination
GET http://localhost:8000/api/guess?it=/mnt/mock-test-files/Final.Destination.MOViE.PACK.1080p.BluRay.x264-HiTSQUAD/The.Final.Destination.1080p.BluRay.x264-METiS/m-fd4-1080p.mkv

### The Incredible Hulk
GET http://localhost:8000/api/guess?it=/mnt/mock-test-files/Marvel.Cinematic.Universe.Phase.01-04.1080p.BluRay.10Bit.X265.DD.5.1-Chivaman/The.Incredible.Hulk.2008.1080p.BluRay.10Bit.X265.DD.5.1-Chivaman.mkv

### Stakeland II
GET http://localhost:8000/api/guess?it=/watch/Stake.Land.II.2016.1080p.BluRay.x264-PSYCHD/Subs/Stake.Land.II.2016.1080p.BluRay.x264-PSYCHD.idx

### Possessed (2000)
GET http://localhost:8000/api/guess?it=/watch/Stake.Land.II.2016.1080p.BluRay.x264-PSYCHD/Subs/Stake.Land.II.2016.1080p.BluRay.x264-PSYCHD.idx

### Health Check
GET http://localhost:8000/api/health

### Statistics
GET http://localhost:8000/api/statistics

### Media Info
GET http://localhost:8000/api/media-info?title=Possessed&year=2000&media_type=movie
